refactor: prevent from pushing to main branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Prevent from pushing to 'main|develop' branches.
+BRANCH=`git rev-parse --abbrev-ref HEAD`
+PROTECTED_BRANCHES="^(main|develop)"
+
+if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
+then
+  echo -e "\n --->  Cannot push to remote '$BRANCH' branch, please create your own branch and use PR.\n" && exit 1
+fi
+exit 0
+
+# Run lint-staged.
 npx lint-staged
